name: Build and Publish to Cloudflare Pages

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - 'release/*'
  
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.117.0
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          
      - name: Build
        run: hugo --minify --gc
      
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: kazakov-xyz
          directory: ./public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
